version: "3.3"

services:
  paper:
    image: "jcxldn/minecraft-runner:paper"
    container_name: "paper"
    command:
      - "-Xmx1024M"
      - "-Xms1024M"
    ports:
      - "25565:25565"
    volumes:
      - "./data:/data"