name: builder

on:
  push:
    branches: master

jobs:
  builder:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Login to Docker Hub
        run: echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin
      - 
        name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      -
        name: List Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      -
        name: Run Buildx (base-papermc)
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x \
            --output "type=image,push=true" \
            -f common/papermc/base.Dockerfile -t jcxldn/minecraft-runner:base-papermc .
      -
        name: Run Buildx (paper)
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x \
            --output "type=image,push=true" \
            -f paper/Dockerfile -t jcxldn/minecraft-runner:paper .
      -
        name: Run Buildx (waterfall)
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x \
            --output "type=image,push=true" \
            -f waterfall/Dockerfile -t jcxldn/minecraft-runner:waterfall .